'use client'

import * as React from 'react'
import { useRouter } from 'next/navigation'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Select } from '@/components/ui/select'
import { Textarea } from '@/components/ui/textarea'
import { Field } from '@/components/forms/Field'
import { EXPORT_DATASETS, DataExportSchema } from '@/lib/validation/schemas'
import { postJson, firstFieldError } from '@/lib/client/api'

// Request a data export. Enqueues a job; the background worker generates the file.
export function ExportRequestForm() {
  const router = useRouter()
  const [errors, setErrors] = React.useState<Record<string, string>>({})
  const [saving, setSaving] = React.useState(false)

  async function onSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault()
    setErrors({})
    const raw = Object.fromEntries(new FormData(e.currentTarget).entries())
    const parsed = DataExportSchema.safeParse(raw)
    if (!parsed.success) {
      const fe = parsed.error.flatten().fieldErrors
      setErrors(Object.fromEntries(Object.entries(fe).map(([k, val]) => [k, val?.[0] ?? 'Invalid'])))
      return
    }
    setSaving(true)
    const res = await postJson<{ export: { id: string } }>('/api/admin/exports', parsed.data)
    setSaving(false)
    if (!res.ok) {
      const fe = firstFieldError(res.error)
      if (fe.field) setErrors({ [fe.field]: fe.message })
      toast.error(fe.message)
      return
    }
    toast.success('Export requested. The file is generated by a background job and will appear as “ready”.')
    router.refresh()
  }

  return (
    <form onSubmit={onSubmit} className="space-y-4" noValidate>
      <div className="grid gap-4 sm:grid-cols-2">
        <Field id="dataset" label="Dataset" required error={errors.dataset}>
          <Select name="dataset" defaultValue={EXPORT_DATASETS[0]}>
            {EXPORT_DATASETS.map((d) => (
              <option key={d} value={d}>{d}</option>
            ))}
          </Select>
        </Field>
        <Field id="format" label="Format" required error={errors.format}>
          <Select name="format" defaultValue="csv">
            <option value="csv">csv</option>
            <option value="json">json</option>
          </Select>
        </Field>
      </div>
      <Field id="notes" label="Notes" hint="Optional — why this export is needed." error={errors.notes}>
        <Textarea name="notes" rows={3} placeholder="Reason / scope for this export request." />
      </Field>
      <div className="flex justify-end">
        <Button type="submit" disabled={saving}>{saving ? 'Requesting…' : 'Request export'}</Button>
      </div>
    </form>
  )
}
